AWSTemplateFormatVersion: '2010-09-09'
Description: 'VPC Endpoints for AWS Services'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'prod']
  
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC where the resources will be deployed.

  RouteTableId:
    Type: String
    Description: The ID of the route table for the private subnets (needed for S3 Gateway endpoint)
    Default: ''

Conditions:
  IsDev: !Equals [!Ref Environment, 'dev']
  HasRouteTable: !Not [!Equals [!Ref RouteTableId, '']]

Resources:
  SecretsManagerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.secretsmanager'
      VpcEndpointType: Interface
      SubnetIds:
        - subnet-2655df7b  # Your private subnets
        - subnet-e22085a8
        - subnet-badfdd91
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'crow-detector-secretsmanager-endpoint-${Environment}'

  ECRAPIEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.api'
      VpcEndpointType: Interface
      SubnetIds:
        - subnet-2655df7b  # Your private subnets
        - subnet-e22085a8
        - subnet-badfdd91
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'crow-detector-ecr-api-endpoint-${Environment}'

  ECRDockerEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.ecr.dkr'
      VpcEndpointType: Interface
      SubnetIds:
        - subnet-2655df7b  # Your private subnets
        - subnet-e22085a8
        - subnet-badfdd91
      SecurityGroupIds:
        - !Ref VPCEndpointSecurityGroup
      PrivateDnsEnabled: true
      Tags:
        - Key: Name
          Value: !Sub 'crow-detector-ecr-docker-endpoint-${Environment}'

  S3GatewayEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Condition: HasRouteTable
    Properties:
      VpcId: !Ref VpcId
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      RouteTableIds:
        - !Ref RouteTableId
      Tags:
        - Key: Name
          Value: !Sub 'crow-detector-s3-gateway-endpoint-${Environment}'

  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub 'crow-detector-vpce-sg-${Environment}'
      GroupDescription: Security group for VPC endpoints
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          SourceSecurityGroupId: !If 
            - IsDev
            - !ImportValue crow-detector-ecs-sg-dev
            - !ImportValue crow-detector-ecs-sg-prod
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0

Outputs:
  SecretsManagerEndpointId:
    Description: ID of the Secrets Manager VPC endpoint
    Value: !Ref SecretsManagerEndpoint
    Export:
      Name: !Sub 'crow-detector-secretsmanager-endpoint-${Environment}'

  ECRAPIEndpointId:
    Description: ID of the ECR API VPC endpoint
    Value: !Ref ECRAPIEndpoint
    Export:
      Name: !Sub 'crow-detector-ecr-api-endpoint-${Environment}'

  ECRDockerEndpointId:
    Description: ID of the ECR Docker VPC endpoint
    Value: !Ref ECRDockerEndpoint
    Export:
      Name: !Sub 'crow-detector-ecr-docker-endpoint-${Environment}'

  S3GatewayEndpointId:
    Description: ID of the S3 Gateway VPC endpoint
    Value: !If [HasRouteTable, !Ref S3GatewayEndpoint, !Ref 'AWS::NoValue']
    Export:
      Name: !Sub 'crow-detector-s3-gateway-endpoint-${Environment}'
    Condition: HasRouteTable

  VPCEndpointSecurityGroupId:
    Description: ID of the VPC endpoint security group
    Value: !Ref VPCEndpointSecurityGroup
    Export:
      Name: !Sub 'crow-detector-vpce-sg-${Environment}'
