AWSTemplateFormatVersion: '2010-09-09'
Description: 'ECS Task Definition for Crow Detector Server'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - prod
  
  ContainerImage:
    Type: String
    Description: The URI of the container image to deploy

Mappings:
  EnvConfig:
    dev:
      Subnets:
        - !ImportValue 'aws-infra-private-subnet-1-id'
        - !ImportValue 'aws-infra-private-subnet-2-id'
        - !ImportValue 'aws-infra-private-subnet-3-id'
      SecurityGroupExport: aws-infra-ecs-sg-id
      LogLevel: 'info'
      Cpu: 256
      Memory: 512
    prod:
      Subnets:
        - !ImportValue 'aws-infra-private-subnet-1-id'
        - !ImportValue 'aws-infra-private-subnet-2-id'
        - !ImportValue 'aws-infra-private-subnet-3-id'
      SecurityGroupExport: aws-infra-ecs-sg-id
      LogLevel: 'warn'
      Cpu: 512
      Memory: 1024

Conditions:
  IsDev: !Equals [!Ref Environment, 'dev']

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub 'crow-detector-task-${Environment}'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: !FindInMap [EnvConfig, !Ref Environment, Cpu]
      Memory: !FindInMap [EnvConfig, !Ref Environment, Memory]
      ExecutionRoleArn: !If 
        - IsDev
        - !ImportValue crow-detector-iam-roles-dev-TaskExecutionRoleArn
        - !ImportValue crow-detector-iam-roles-prod-TaskExecutionRoleArn
      TaskRoleArn: !If 
        - IsDev
        - !ImportValue crow-detector-iam-roles-dev-TaskRoleArn
        - !ImportValue crow-detector-iam-roles-prod-TaskRoleArn
      ContainerDefinitions:
        - Name: crow-detector-app
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 3000
              Protocol: tcp
          Environment:
            - Name: NODE_ENV
              Value: !Ref Environment
            - Name: PORT
              Value: '3000'
            - Name: RDS_HOST
              Value: !ImportValue 'crow-detector-db-dev-endpoint'
            - Name: RDS_DATABASE
              Value: !ImportValue 'crow-detector-db-dev-name'
          Secrets:
            - Name: RDS_USERNAME
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:crow-detector-db-${Environment}:username::'
            - Name: RDS_PASSWORD
              ValueFrom: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:crow-detector-db-${Environment}:password::'
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Sub '/ecs/crow-detector-${Environment}'
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          HealthCheck:
            Command:
              - CMD-SHELL
              - 'node -e "require(\"http\").get(\"http://localhost:3000/health\", (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"'
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60

  ECSService:
    Type: AWS::ECS::Service
    Properties:
      ServiceName: !Sub 'crow-detector-service-${Environment}'
      Cluster: !Sub 'crow-detector-${Environment}'
      TaskDefinition: !Ref TaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      LoadBalancers:
        - TargetGroupArn: !If 
            - IsDev
            - !ImportValue crow-detector-tg-dev-Arn
            - !ImportValue crow-detector-tg-prod-Arn
          ContainerName: crow-detector-app
          ContainerPort: 3000
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: DISABLED
          SecurityGroups:
            - !ImportValue 'aws-infra-ecs-sg-id'
          Subnets:
            - !ImportValue 'aws-infra-private-subnet-1-id'
            - !ImportValue 'aws-infra-private-subnet-2-id'
            - !ImportValue 'aws-infra-private-subnet-3-id'

Outputs:
  TaskDefinitionArn:
    Description: The ARN of the ECS task definition
    Value: !Ref TaskDefinition
    Export:
      Name: !Sub '${AWS::StackName}-TaskDefinitionArn'

  ServiceName:
    Description: The name of the ECS service
    Value: !Ref ECSService
    Export:
      Name: !Sub '${AWS::StackName}-ServiceName' 