AWSTemplateFormatVersion: '2010-09-09'
Description: 'Crow Detector S3 Buckets for Image Storage'

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues: [dev, prod]
    Description: Environment name (dev or prod)
  
  BucketName:
    Type: String
    Default: crow-detector-images
    Description: Base name for the S3 bucket

Resources:
  CrowDetectorImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${BucketName}-${Environment}'
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LifecycleConfiguration:
        Rules:
          - Id: DeleteOldImages
            Status: Enabled
            ExpirationInDays: 365
            NoncurrentVersionExpirationInDays: 30
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ['*']
            AllowedMethods: [GET, PUT, POST, DELETE]
            AllowedOrigins: ['*']
            MaxAge: 3000

  CrowDetectorImagesBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref CrowDetectorImagesBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyUnencryptedObjectUploads
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Sub '${CrowDetectorImagesBucket.Arn}/*'
            Condition:
              StringNotEquals:
                's3:x-amz-server-side-encryption': 'AES256'
          - Sid: DenyObjectUploadsWithoutEncryption
            Effect: Deny
            Principal: '*'
            Action: s3:PutObject
            Resource: !Sub '${CrowDetectorImagesBucket.Arn}/*'
            Condition:
              'Null':
                's3:x-amz-server-side-encryption': 'true'

Outputs:
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref CrowDetectorImagesBucket
    Export:
      Name: !Sub '${AWS::StackName}-BucketName'
  
  BucketArn:
    Description: ARN of the S3 bucket
    Value: !GetAtt CrowDetectorImagesBucket.Arn
    Export:
      Name: !Sub '${AWS::StackName}-BucketArn'
  

