AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - prod

Resources:
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'crow-detector-ecs-cluster-${Environment}-TaskExecutionRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: SecretsAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource: !Sub 'arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:crow-detector-db-${Environment}*'

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'crow-detector-ecs-cluster-${Environment}-TaskRole'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

Outputs:
  TaskExecutionRoleArn:
    Description: The ARN of the ECS task execution role
    Value: !GetAtt TaskExecutionRole.Arn
    Export:
      Name: !Sub 'crow-detector-iam-roles-${Environment}-TaskExecutionRoleArn'

  TaskRoleArn:
    Description: The ARN of the ECS task role
    Value: !GetAtt TaskRole.Arn
    Export:
      Name: !Sub 'crow-detector-iam-roles-${Environment}-TaskRoleArn' 