AWSTemplateFormatVersion: '2010-09-09'
Description: 'Crow Detector RDS Database in aws-infra VPC'

Parameters:
  Environment:
    Type: String
    Default: 'dev'
    AllowedValues: ['dev', 'prod']
    Description: 'Environment name'
    
  DatabaseInstanceClass:
    Type: String
    Default: 'db.t3.micro'
    AllowedValues: ['db.t3.micro', 'db.t3.small', 'db.t3.medium', 'db.r5.large']
    Description: 'Database instance class'

Resources:
  DatabaseInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Snapshot
    UpdateReplacePolicy: Snapshot
    Properties:
      DBInstanceIdentifier: !Sub 'crow-detector-db-${Environment}'
      DBInstanceClass: !Ref DatabaseInstanceClass
      Engine: 'postgres'
      EngineVersion: '17.5'
      DBName: !Sub 'crow_detector_db_${Environment}'
      MasterUsername: !Sub '{{resolve:secretsmanager:crow-detector-db-${Environment}:SecretString:username}}'
      MasterUserPassword: !Sub '{{resolve:secretsmanager:crow-detector-db-${Environment}:SecretString:password}}'
      DBSubnetGroupName: !ImportValue 'aws-infra-rds-subnet-group-name'
      VPCSecurityGroups:
        - !ImportValue 'aws-infra-db-sg-id'
      AllocatedStorage: 20
      StorageType: gp2
      StorageEncrypted: true
      BackupRetentionPeriod: 7
      MultiAZ: false
      PubliclyAccessible: false
      Tags:
        - Key: Name
          Value: !Sub 'crow-detector-db-${Environment}'
        - Key: Environment
          Value: !Ref Environment
        - Key: Project
          Value: 'crow-detector'

Outputs:
  DatabaseEndpoint:
    Description: 'Database connection endpoint'
    Value: !GetAtt DatabaseInstance.Endpoint.Address
    Export:
      Name: !Sub 'crow-detector-db-${Environment}-endpoint'
  
  DatabasePort:
    Description: 'Database port'
    Value: !GetAtt DatabaseInstance.Endpoint.Port
    Export:
      Name: !Sub 'crow-detector-db-${Environment}-port'
  
  DatabaseName:
    Description: 'Database name'
    Value: !Sub 'crow_detector_db_${Environment}'
    Export:
      Name: !Sub 'crow-detector-db-${Environment}-name'
