name: Deploy On Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to ECS Fargate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm ci

      - name: Lint Code
        run: npm run lint

      - name: Run Unit Tests
        run: npm test

      - name: Build Application
        run: npm run build

      - name: Set Up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Log Into AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build Docker Image
        run: |
          docker build -t crow-detector-server:$GITHUB_SHA .
          docker tag crow-detector-server:$GITHUB_SHA ${{ steps.login-ecr.outputs.registry }}/crow-detector-server-dev:$GITHUB_SHA

      - name: Push Docker Image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/crow-detector-server-dev:$GITHUB_SHA
          echo "CONTAINER_IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/crow-detector-server-dev:$GITHUB_SHA" >> $GITHUB_ENV

      - name: Deploy ECS Task Definition to Dev
        run: |
          aws cloudformation deploy \
            --stack-name crow-detector-task-stack-dev \
            --template-file cloudformation/crow-detector-ecs-task.yaml \
            --parameter-overrides ContainerImage=${{ env.CONTAINER_IMAGE_URI }} Environment=dev \
            --capabilities CAPABILITY_NAMED_IAM \
            --region us-west-2
